### PR TITLE
Feat/peit 03 banner

### PR DESCRIPTION
**Pull request by ZoeG00**
## Description
Banner component. 
Carousel created with **react-responsive-carousel**. 
Its function is to move different images

### Trello link
[PEIT-03-Banner](https://trello.com/c/jFVVz2ko)

## Changes añadidos
- Create **Banner** component at src/Components/Banner.
- Create the files **Banner.jsx**, **ImageSlider.jsx** & **SlideData.js**.
- Add the images for the carousel at src/assets/banner.
- Add **Banner** component in `app.jsx`

## Screenshots
banner
banner2

### CODE REVIEW

**Review by mikejbp — APPROVED** [review]
Excelente trabajo, Zoe!

**Review by freakAyLl — APPROVED** [review]
Esta god Zoe!

**Comment by Edisonmunoz13** [comment]
Espectacular Zoe!!

**Review by Edisonmunoz13 — APPROVED** [review]
Ahora si! Espectacular Zoe!

**Pull request merged**
